### ISSUE TITLE
FR9. Current Location

### ISSUE THREAD

**Issue by VTarver21** [WSU-4110/GPSAndroid#4]
|FR9.  Current Location|
|---|
|**Goal**: The goal is to enable the user to see where they are on the map.
**Stakeholders:** WSU Students/Faculty|
| **Description:** Users will be able to see where they are on the map and/or how close they are to a building or landmark.|
| **Origin:** Team members came up with this during the second meeting.|
| **Version:** 1.0  |
|**Date:** 05/30/2021
|  **Priority:** 2 |

**Comment by sabdall33** [comment]
Current Location function and feature added.
